before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build cs203S2020_syllabus.tex
deploy:
  provider: releases
  api_key:
    secure: H5xjt2+2V2pvi5a9D8ZGQf6h9RaItHIQDG9uTopRCvDlQMsX5Xx+13WHcSoMmlvoj5PEaHM4il2EtBJJeEPrhgmzEBeSG7PaDs4dZPi6XugGBZCVU2tua9gA+1/c6fD4f/IkMXLTWMWzk5M16ExboBW2T/hrURlfIVjjj3EQ4fLRG82GJJcnfvEuWAKJMbfDd1Al4SqeH86bSa4R/QFl1NnV2FyILrQxTHO7y4VqUWA4yio5FT7yMtp/nTTImMZHcYMkgX/OmZxlbsC6XaIizB3LlAp16A5DQ6OUYSRsvQRYRw1qsOFrjhNZkTvAfYdWoyN4l7HnJK3SSrkvNhKInTBXQdMGbixkduNWhRV/UOqNCFpzYZovQy34vFgfbVAPExy1YAqqTSDy6Ap3BtAgp8cGilNkBPR/sjeb6K653ayhtOJirOe9mVjEIeba30JqG1BMurw8cG25IA2JIVnZonOgVlC30lkdERzA1pshnkBkZRme589tpQ+mAnXw2UxoLM2gqkQpk2qXKqXl65zNqBGLPUSM1oAsoUho+AEjuik365yi+gv4qfgm6eQX+k2SPTMNvu97oVCsHg6Bgrb8E0+6bR3lT4BC80FrbCGtnXUNLGdSDWPf60V+6z1YuhN6opS84jk+sQF7QXQ4toFKLfZvLh5H3GIjCJeccQHjVto=
  file: _build/cs203S2020_syllabus.pdf
  skip_cleanup: true
  on:
    tags: true
